services:
  fastapi-app:
    container_name: fastapi-app
    build: .
    image: fast_api_base

    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: /bin/bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
